// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static String _getEnvVar(String key) {
    final value = dotenv.env[key];
    if (value == null || value.isEmpty) {
      throw Exception('Environment variable $key is not set in .env file');
    }
    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _getEnvVar('FIREBASE_API_KEY'),
    appId: _getEnvVar('FIREBASE_APP_ID'),
    messagingSenderId: _getEnvVar('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _getEnvVar('FIREBASE_PROJECT_ID'),
    authDomain: _getEnvVar('FIREBASE_AUTH_DOMAIN'),
    storageBucket: _getEnvVar('FIREBASE_STORAGE_BUCKET'),
    databaseURL: _getEnvVar('FIREBASE_DATABASE_URL'),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _getEnvVar('FIREBASE_API_KEY'),
    appId: _getEnvVar('FIREBASE_APP_ID'),
    messagingSenderId: _getEnvVar('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _getEnvVar('FIREBASE_PROJECT_ID'),
    storageBucket: _getEnvVar('FIREBASE_STORAGE_BUCKET'),
    databaseURL: _getEnvVar('FIREBASE_DATABASE_URL'),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _getEnvVar('FIREBASE_API_KEY'),
    appId: _getEnvVar('FIREBASE_APP_ID'),
    messagingSenderId: _getEnvVar('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _getEnvVar('FIREBASE_PROJECT_ID'),
    storageBucket: _getEnvVar('FIREBASE_STORAGE_BUCKET'),
    databaseURL: _getEnvVar('FIREBASE_DATABASE_URL'),
    iosClientId: _getEnvVar('FIREBASE_IOS_CLIENT_ID'),
    iosBundleId: _getEnvVar('FIREBASE_IOS_BUNDLE_ID'),
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _getEnvVar('FIREBASE_API_KEY'),
    appId: _getEnvVar('FIREBASE_APP_ID'),
    messagingSenderId: _getEnvVar('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _getEnvVar('FIREBASE_PROJECT_ID'),
    storageBucket: _getEnvVar('FIREBASE_STORAGE_BUCKET'),
    databaseURL: _getEnvVar('FIREBASE_DATABASE_URL'),
    iosBundleId: _getEnvVar('FIREBASE_IOS_BUNDLE_ID'),
  );
}
