// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static String _getEnvVar(String key) {
    final value = dotenv.env[key];
    if (value == null || value.isEmpty) {
      throw Exception('Environment variable $key is not set in .env file');
    }
    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _getEnvVar('FIREBASE_API_KEY'),
    appId: _getEnvVar('FIREBASE_APP_ID'),
    messagingSenderId: _getEnvVar('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _getEnvVar('FIREBASE_PROJECT_ID'),
    authDomain: _getEnvVar('FIREBASE_AUTH_DOMAIN'),
    storageBucket: _getEnvVar('FIREBASE_STORAGE_BUCKET'),
    databaseURL: _getEnvVar('FIREBASE_DATABASE_URL'),
  );
}
